name: Feature request
description: Suggest an idea or enhancement for the integration
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    validations:
      required: true
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of the problem. Ex. I'm frustrated when [...]

  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: Describe the solution you'd like

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered

  - type: input
    id: vacuum-model
    attributes:
      label: Vacuum model (if relevant)
      placeholder: e.g. dreame.vacuum.p2028

  - type: textarea
    id: extra
    attributes:
      label: Additional context
