---
name: Hassfest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate manifest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@e91ad1948e57189485b9c1ad608af0c303946f89  # master 2026-01-30
